### ISSUE TITLE
nl.hyranasoftware.githubupdater is lacking

### ISSUE THREAD

**Issue by laerreal** [eternia16/javaGMR#13]
I cannot compile the project because of `nl.hyranasoftware.githubupdater` is lacking. Where to get it?

**Comment by laerreal** [comment]
I managed to build it without updater. Branch `build_fixes` in [my fork](https://github.com/laerreal/javaGMR) refers to commits which could be useful.

**Comment by sanguine-my-brother** [comment]
Unfortunately, I don't have access to a maven repo, but githubupdater can be found here: https://github.com/eternia16/javaGithubUpdater. I'll take a look at your build_fixes branch.

**Comment by laerreal** [comment]
Addition of the updater as Git submodule is a way to solve the problem.

**Comment by sanguine-my-brother** [comment]
Personally, I've never heard of Git submodules before, but looking it currently up and yes it would indeed solve the dependency problem. 👍

**Comment by sanguine-my-brother** [comment]
I'm marking this as resolved for now, I noticed in one of your commits you already added the Git submodule so I'll gently await your pull request.
