### ISSUE TITLE
"Remove Lock" Button Not Working

### ISSUE THREAD

**Issue by padoura** [eternia16/javaGMR#27]
## Expected behavior ##
Clicking the "Remove lock" button should delete the lock file.
## actual behavior. ##
If download/upload stops due to connection error, the "Remove lock" does not delete it, preventing the user from downloading/uploading other games.

**Comment by sanguine-my-brother** [comment]
Recognized this bug as well. Will be fixed in the next milestone! 😏

**Comment by padoura** [comment]
Fixed since v1.1.3.
