### ISSUE TITLE
Authorization Code Deleted

### ISSUE THREAD

**Issue by padoura** [eternia16/javaGMR#28]
## Expected behavior ##
Authorization code remains stored in the configuration file.
## actual behavior. ##
Authorization code is sometimes deleted (replaced by null in the configuration file).

**Comment by sanguine-my-brother** [comment]
:p I just experienced this bug as well.

**Comment by silasary** [comment]
I assume it's to do with the client crashing while the file handle is open?

**Comment by sanguine-my-brother** [comment]
I'll fix this bug during the Veneficus update.

**Comment by padoura** [comment]
## Steps to reproduce the problem. ##
Whenever the GMR server is inaccessible (site down or no internet connection for client).

**Comment by padoura** [comment]
Solved in v1.1.5.
